### ISSUE TITLE
Cannot find module err on bigchaindb-orm@3.0.3

### ISSUE THREAD

**Issue by abbasogaji** [bigchaindb/js-driver-orm#93]
Unable to install bigchaindb javascript driver and ORM properly

````
Please verify that the package.json has a valid "main" entry
?[90m    at tryPackage (internal/modules/cjs/loader.js:297:19)?[39m
?[90m    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)?[39m
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:27)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:686:27)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:848:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:74:18)?[39m
    at Object.<anonymous> (D:\USLUSER\Documents\PROJECTS\PERSONAL\APP\NESTJS\test-bchain\node_modules\?[4mbigchaindb-orm?[24m\dist\node\index.js:15:25)
?[90m    at Module._compile (internal/modules/cjs/loader.js:955:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:811:32)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  path: ?[32m'D:\\USLUSER\\Documents\\PROJECTS\\PERSONAL\\APP\\NESTJS\\test-bchain\\node_modules\\bigchaindb-orm\\node_modules\\bigchaindb-driver\\package.json'?[39m,
  requestPath: ?[32m'bigchaindb-driver'?[39m
}
````

**Comment by diegotorreslopez81** [comment]
Same issue here...any solution?

**Comment by abbasogaji** [comment]
@diegotorreslopez81 dont use the driver, use the bigchaindb SDk directly
